# Generated by Django 3.0.8 on 2020-08-20 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2020, 8, 20, 17, 34, 25, 560187, tzinfo=utc), max_length=40, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Last name'),
            preserve_default=False,
        ),
    ]
